### PR TITLE
Add support for Python 3.8 (fixes #7)

### LINKED ISSUE #7: Doesn't work under Python 3.8
```
test_whatever.py:2: in <module>
    from whatever import _, that
whatever.py:21: in <module>
    class Whatever(object):
whatever.py:29: in Whatever
    __code__ = CodeType(*((1, 1) if PY2 else (1, 0, 1)) +
E   TypeError: code() takes at least 14 arguments (13 given)
```

### PR DESCRIPTION
**Pull request by felixonmars**

### CODE REVIEW

**Comment by ncopa** [comment]
I just bumped into this problem. However, the test suite still fails, even with the patch applied.

```
======================================================== ERRORS ========================================================
__________________________________________ ERROR collecting test_whatever.py ___________________________________________
/usr/lib/python3.8/site-packages/_pytest/python.py:512: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python3.8/site-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:655: in _load_unlocked
    ???
<frozen importlib._bootstrap>:618: in _load_backward_compatible
    ???
/usr/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:301: in load_module
    exec(co, mod.__dict__)
test_whatever.py:2: in <module>
    from whatever import _, that
E     File "/home/ncopa/aports/testing/py3-whatever/src/whatever-0.5/whatever.py", line 34
E       class WhateverCode(object):
E       ^
E   SyntaxError: invalid syntax
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================== 1 error in 0.40 seconds =============================
```

**Comment by Suor** [comment]
Yes, you broke syntax for all Pythons I guess )

**Comment by Suor** [comment]
BTW, if you want to add new Pythons properly you'll need to add them to tox and travis, so that they'll be tested too.

You may drop all Python 2s if it will make it easier for you. It's not too far for EOL anyway.

**Comment by felixonmars** [comment]
Sorry I yolo-pushed this on github web with a simple bracket error. It should have been fixed now.

There is still an error related to flakes though, not sure what I should do to fix it.

**Comment by Suor** [comment]
Released, thanks @felixonmars.

**Pull request merged**
